spring:
  datasource:
    driverClassName: org.h2.Driver    
    url: jdbc:h2:file:./testdb
    username: sa
    #password: ENC(SIdxOSVy6APkNDemmgHTcw3fZVdFTFGy)
    password: '{cipher}5c34cf47a22616bb228e503efb5fe0397cb03e6a7006e532b3797f3c7ba93fcd'
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    config: # Ex) `http://localhost:8088/config/test`
      name: config # config name
      profile: dev # config profile
      
taeng:
  profile: I'm dev taeng
  comment: Hello! updated by Spring Bus with webhook!!
  pwd: '{cipher}5c34cf47a22616bb228e503efb5fe0397cb03e6a7006e532b3797f3c7ba93fcd'
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
